spring.application.name=product-api

# MySQL database connection URL
# localhost = database running on same machine
# 3306 = default MySQL port
# productdb = database name created inside Docker
spring.datasource.url=jdbc:mysql://localhost:3306/productdb

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=root

# MySQL JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automatically create/update database tables from entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in IntelliJ console
spring.jpa.show-sql=true

# Format SQL nicely in logs
spring.jpa.properties.hibernate.format_sql=true

# Application server port
server.port=8080

app.jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckp3dFRva2VuU2lnbmluZ1Rlc3QxMjM0NTY3ODkw
app.jwt.expiration-ms=3600000
