apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: product-api
spec:
  # Minikube can bind this PVC to local cluster storage automatically.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
