apiVersion: v1
kind: Secret
metadata:
  name: product-api-secret
  namespace: product-api
type: Opaque
stringData:
  # Secrets injected into the Spring Boot pod at runtime.
  SPRING_DATASOURCE_PASSWORD: root
  APP_JWT_SECRET: VGhpc0lzQVNlY3JldEtleUZvckp3dFRva2VuU2lnbmluZ1Rlc3QxMjM0NTY3ODkw
